In [2]:
import numpy as np

scalar =np.array(42)
print(scalar)
scalar.ndim

42


0

In [5]:
vector =np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [7]:
matriz =np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [8]:
tensor =np.array([[[1,2,3],[4,5,6],[7,8,9],[0,2,45]],[[1,2,3],[4,5,6],[7,8,9],[0,2,45]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]]


3